FROM ubuntu:22.04

# install miniconda
RUN apt-get update \
    && apt-get install -y build-essential \
    && apt-get install -y wget \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

ENV CONDA_DIR /opt/conda
RUN wget --quiet https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O ~/miniconda.sh && \
    /bin/bash ~/miniconda.sh -b -p /opt/conda

# Put conda in path so we can use conda activate
ENV PATH=$CONDA_DIR/bin:$PATH

# install aviary and dependencies. Match this invocation to the documentation
RUN conda create -y -c conda-forge -c bioconda -n aviary --strict-channel-priority --override-channels aviary'='0.13.0

# Download some example data so we can test the installation
RUN wget https://github.com/rhysnewell/aviary/raw/main/test/data/wgsim.1.fq.gz
RUN wget https://github.com/rhysnewell/aviary/raw/main/test/data/wgsim.2.fq.gz

# activate the aviary environment
RUN echo "source activate aviary" > ~/.bashrc
ENV PATH=$CONDA_DIR/envs/aviary/bin:$PATH

# Run aviary assemble with megahit (fast) on the test reads
RUN aviary assemble \
    -1 wgsim.1.fq.gz \
    -2 wgsim.2.fq.gz \
    --use-megahit \
    --skip-qc \
    -o aviary_test_out \
    -n 4 -t 4
